describe("Error System", function()
    local errors = require("jade.errors")

    describe("JadeError", function()
        it("creates error with code and message", function()
            local err = errors.JadeError.new("J0001", "Test error", { key = "value" })
            assert.are.equal("J0001", err.code)
            assert.are.equal("Test error", err.message)
            assert.are.equal("value", err.details.key)
        end)

        it("converts to string", function()
            local err = errors.JadeError.new("J0001", "Test error")
            assert.are.equal("[J0001] Test error", tostring(err))
        end)

        it("converts to JSON", function()
            local err = errors.JadeError.new("J0001", "Test error", { key = "value" })
            local json = err:toJSON()
            assert.are.equal("J0001", json.code)
            assert.are.equal("Test error", json.message)
            assert.are.equal("value", json.details.key)
        end)

        it("formats message with details", function()
            local err = errors.JadeError.new("J0001", "Error", { host = "localhost", port = 5432 })
            local msg = err:format("Connection to {host}:{port} failed")
            assert.are.equal("Connection to localhost:5432 failed", msg)
        end)
    end)

    describe("Error codes", function()
        it("has all connection error codes", function()
            assert.are.equal("J0001", errors.AUTHENTICATION_FAILED)
            assert.are.equal("J0002", errors.CONNECTION_REFUSED)
            assert.are.equal("J0003", errors.CONNECTION_TIMEOUT)
            assert.are.equal("J0004", errors.DATABASE_NOT_FOUND)
        end)

        it("has all query error codes", function()
            assert.are.equal("J1000", errors.QUERY_SYNTAX_ERROR)
            assert.are.equal("J1008", errors.NO_ROWS_FOUND)
            assert.are.equal("J1016", errors.UNIQUE_CONSTRAINT_VIOLATION)
        end)

        it("has all migration error codes", function()
            assert.are.equal("J2000", errors.MIGRATION_FAILED)
            assert.are.equal("J2002", errors.MIGRATION_ALREADY_APPLIED)
        end)

        it("has all security error codes", function()
            assert.are.equal("J5000", errors.SQL_INJECTION_DETECTED)
            assert.are.equal("J5001", errors.INVALID_IDENTIFIER)
        end)
    end)

    describe("Error factories", function()
        it("creates ConnectionError", function()
            local err = errors.ConnectionError("J0001", { host = "localhost" })
            assert.is_not_nil(err)
            assert.are.equal("J0001", err.code)
        end)

        it("creates QueryError", function()
            local err = errors.QueryError("J1008", { table = "users" })
            assert.is_not_nil(err)
            assert.are.equal("J1008", err.code)
        end)

        it("creates MigrationError", function()
            local err = errors.MigrationError("J2000", { name = "init" })
            assert.is_not_nil(err)
            assert.are.equal("J2000", err.code)
        end)

        it("creates SecurityError", function()
            local err = errors.SecurityError("J5000", { pattern = "OR" })
            assert.is_not_nil(err)
            assert.are.equal("J5000", err.code)
        end)
    end)

    describe("Error messages", function()
        it("gets message for error code", function()
            local msg = errors.getMessage("J0001", { host = "localhost", user = "admin" })
            assert.is_truth(msg:match("localhost"))
            assert.is_truth(msg:match("admin"))
        end)

        it("returns unknown for invalid code", function()
            local msg = errors.getMessage("J9999")
            assert.is_truth(msg:match("Unknown error"))
        end)

        it("preserves literal percent in details (#184)", function()
            local msg = errors.getMessage("J1020", { details = "discount is 100%" })
            assert.is_truth(msg:find("discount is 100%", 1, true))
        end)

        it("preserves %s and other percent sequences in details (#184)", function()
            local msg = errors.getMessage("J1019", { error = "expected %s got %d" })
            assert.is_truth(msg:find("expected %s got %d", 1, true))
        end)

        it("preserves lone percent at end of details (#184)", function()
            local msg = errors.getMessage("J5004", { details = "progress 50%" })
            assert.is_truth(msg:find("progress 50%", 1, true))
        end)

        it("build/raise keeps percent literals in message (#184)", function()
            local ok, err = pcall(function()
                errors.raise(errors.INVALID_INPUT, { details = "rate 100% ok" })
            end)
            assert.is_false(ok)
            assert.is_truth(err.message:find("rate 100% ok", 1, true))
        end)
    end)

    describe("raise", function()
        it("raises a typed error with code", function()
            local ok, err = pcall(function()
                errors.raise(errors.NO_ROWS_FOUND, { table = "users" })
            end)
            assert.is_false(ok)
            assert.are.equal("table", type(err))
            assert.are.equal("J1008", err.code)
            assert.is_truth(err.message:match("users"))
        end)

        it("aliases unique violation to J1016", function()
            assert.are.equal(errors.UNIQUE_CONSTRAINT_VIOLATION, errors.UNIQUE_VIOLATION)
            assert.are.equal("J1016", errors.UNIQUE_VIOLATION)
        end)

        it("aliases row not found to J1008", function()
            assert.are.equal(errors.NO_ROWS_FOUND, errors.ROW_NOT_FOUND)
        end)
    end)

    describe("classifyDriverError", function()
        it("maps auth failures", function()
            assert.are.equal(errors.AUTHENTICATION_FAILED,
                errors.classifyDriverError("password authentication failed for user"))
        end)

        it("maps unique violations", function()
            assert.are.equal(errors.UNIQUE_CONSTRAINT_VIOLATION,
                errors.classifyDriverError("UNIQUE constraint failed: users.email"))
        end)

        it("maps foreign key violations", function()
            assert.are.equal(errors.FOREIGN_KEY_VIOLATION,
                errors.classifyDriverError("FOREIGN KEY constraint failed"))
        end)

        it("falls back to raw query failed", function()
            assert.are.equal(errors.RAW_QUERY_FAILED,
                errors.classifyDriverError("something unexpected"))
        end)
    end)

    describe("build", function()
        it("builds ConnectionError for J0xxx", function()
            local err = errors.build(errors.CONNECTION_REFUSED, { host = "db", port = 5432 })
            assert.are.equal("J0002", err.code)
            assert.is_truth(err.message:match("db"))
        end)
    end)
end)
