local Column = require("jade.schema.column")

describe("Column", function()
    it("creates a column with type", function()
        local col = Column.new(nil, "string", 120)
        assert.are.equal("string", col.type)
        assert.are.equal(120, col.length)
        assert.is_true(col._nullable)
        assert.is_false(col._unique)
        assert.is_false(col._primary_key)
    end)

    it("chains primaryKey()", function()
        local col = Column.new(nil, "integer"):primaryKey()
        assert.is_true(col._primary_key)
        assert.is_false(col._nullable)
    end)

    it("chains unique()", function()
        local col = Column.new(nil, "string"):unique()
        assert.is_true(col._unique)
    end)

    it("chains notNull()", function()
        local col = Column.new(nil, "string"):notNull()
        assert.is_false(col._nullable)
    end)

    it("chains default()", function()
        local col = Column.new(nil, "boolean"):default(true)
        assert.is_true(col._default)
    end)

    it("chains defaultNow()", function()
        local col = Column.new(nil, "timestamp"):defaultNow()
        assert.are.equal("CURRENT_TIMESTAMP", col._default)
    end)

    it("chains multiple methods", function()
        local col = Column.new(nil, "string", 255)
            :notNull()
            :unique()
            :default("hello")
        assert.is_false(col._nullable)
        assert.is_true(col._unique)
        assert.are.equal("hello", col._default)
    end)

    it("clones a column", function()
        local original = Column.new(nil, "string", 120):notNull()
        local copy = original:clone()
        assert.are.equal(original.type, copy.type)
        assert.are.equal(original.length, copy.length)
        assert.are.equal(original._nullable, copy._nullable)
        -- Modify copy doesn't affect original
        copy.length = 999
        assert.are.equal(120, original.length)
    end)
end)
