describe("Types", function()
    local String = require("jade.types.string")
    local Integer = require("jade.types.integer")
    local Boolean = require("jade.types.boolean")
    local Text = require("jade.types.text")
    local Timestamp = require("jade.types.timestamp")
    local Float = require("jade.types.float")
    local Decimal = require("jade.types.decimal")
    local UUID = require("jade.types.uuid")
    local Date = require("jade.types.date")

    describe("String", function()
        it("creates with default length 255", function()
            local col = String()
            assert.are.equal("string", col.type)
            assert.are.equal(255, col.length)
        end)

        it("creates with custom length", function()
            local col = String(120)
            assert.are.equal(120, col.length)
        end)

        it("supports chaining", function()
            local col = String(100):notNull():unique()
            assert.is_false(col._nullable)
            assert.is_true(col._unique)
        end)
    end)

    describe("Integer", function()
        it("creates integer column", function()
            local col = Integer()
            assert.are.equal("integer", col.type)
        end)

        it("supports primaryKey", function()
            local col = Integer():primaryKey()
            assert.is_true(col._primary_key)
        end)
    end)

    describe("Boolean", function()
        it("creates boolean column", function()
            local col = Boolean()
            assert.are.equal("boolean", col.type)
        end)

        it("supports default", function()
            local col = Boolean():default(true)
            assert.is_true(col._default)
        end)
    end)

    describe("Text", function()
        it("creates text column", function()
            local col = Text()
            assert.are.equal("text", col.type)
        end)
    end)

    describe("Timestamp", function()
        it("creates timestamp column", function()
            local col = Timestamp()
            assert.are.equal("timestamp", col.type)
        end)

        it("supports defaultNow", function()
            local col = Timestamp():defaultNow()
            assert.are.equal("CURRENT_TIMESTAMP", col._default)
        end)
    end)

    describe("Float", function()
        it("creates float column", function()
            local col = Float()
            assert.are.equal("float", col.type)
        end)
    end)

    describe("Decimal", function()
        it("creates with default precision", function()
            local col = Decimal()
            assert.are.equal("decimal", col.type)
            assert.are.equal(10, col.precision)
            assert.are.equal(2, col.scale)
        end)

        it("creates with custom precision", function()
            local col = Decimal(12, 4)
            assert.are.equal(12, col.precision)
            assert.are.equal(4, col.scale)
        end)
    end)

    describe("UUID", function()
        it("creates uuid column", function()
            local col = UUID()
            assert.are.equal("uuid", col.type)
        end)
    end)

    describe("Date", function()
        it("creates date column", function()
            local col = Date()
            assert.are.equal("date", col.type)
        end)
    end)
end)
