local M = {}

-- Generate Jade schema from introspected database
function M.generateSchema(schema)
    local lines = {}

    lines[#lines + 1] = "local jade = require(\"jade\")"
    lines[#lines + 1] = ""
    lines[#lines + 1] = "local schema = {}"
    lines[#lines + 1] = ""

    -- Sort tables alphabetically
    local table_names = {}
    for name in pairs(schema.tables) do
        table_names[#table_names + 1] = name
    end
    table.sort(table_names)

    for _, table_name in ipairs(table_names) do
        local table_def = schema.tables[table_name]
        local entity_code = M.generateEntity(table_name, table_def)
        lines[#lines + 1] = entity_code
        lines[#lines + 1] = ""
    end

    lines[#lines + 1] = "return schema"

    return table.concat(lines, "\n")
end

-- Generate entity definition for a table
function M.generateEntity(table_name, table_def)
    local lines = {}

    -- Entity name (singularize table name)
    local entity_name = table_name:match("^(.-s)$") or table_name

    lines[#lines + 1] = string.format("schema.%s = jade.Entity(\"%s\", {", entity_name, table_name)

    -- Sort columns alphabetically
    local col_names = {}
    for name in pairs(table_def.columns) do
        col_names[#col_names + 1] = name
    end
    table.sort(col_names)

    for _, col_name in ipairs(col_names) do
        local col = table_def.columns[col_name]
        local col_def = M.generateColumn(col_name, col)
        lines[#lines + 1] = "    " .. col_def
    end

    lines[#lines + 1] = "})"

    return table.concat(lines, "\n")
end

-- Generate column definition
function M.generateColumn(col_name, col)
    local parts = {}

    -- Column name
    parts[#parts + 1] = col_name .. " = "

    -- Type
    if col.type == "string" and col.length then
        parts[#parts + 1] = string.format("jade.String(%d)", col.length)
    elseif col.type == "decimal" and col.precision then
        parts[#parts + 1] = string.format("jade.Decimal(%d, %d)", col.precision, col.scale or 0)
    else
        parts[#parts + 1] = "jade." .. col.type:sub(1, 1):upper() .. col.type:sub(2) .. "()"
    end

    -- Modifiers
    if col.primary_key then
        parts[#parts + 1] = ":primaryKey()"
    end

    if col.unique then
        parts[#parts + 1] = ":unique()"
    end

    if not col.nullable and not col.primary_key then
        parts[#parts + 1] = ":notNull()"
    end

    if col.default and not col.auto_increment then
        local default_val = M.formatDefault(col.default, col.type)
        if default_val then
            parts[#parts + 1] = string.format(":default(%s)", default_val)
        end
    end

    return table.concat(parts)
end

-- Format default value
function M.formatDefault(default, col_type)
    if not default then
        return nil
    end

    -- Remove type casts
    default = default:gsub("::%w+", "")

    -- Handle functions
    if default:match("nextval") then
        return nil -- Handled by primaryKey()
    end

    if default == "now()" or default == "CURRENT_TIMESTAMP" then
        return nil -- Handled by defaultNow()
    end

    if default == "true" then
        return "true"
    end

    if default == "false" then
        return "false"
    end

    -- Handle string defaults
    if default:match("^'(.*)'$") then
        return "\"" .. default:match("^'(.*)'$") .. "\""
    end

    -- Handle numbers
    if default:match("^%-?%d+%.?%d*$") then
        return default
    end

    return nil
end

-- Generate migration file content
function M.generateMigration(schema, name)
    local lines = {}

    lines[#lines + 1] = string.format("-- Migration: %s", name)
    lines[#lines + 1] = "-- Generated by Jade introspection"
    lines[#lines + 1] = ""
    lines[#lines + 1] = "local jade = require(\"jade\")"
    lines[#lines + 1] = ""
    lines[#lines + 1] = "local M = {}"
    lines[#lines + 1] = ""
    lines[#lines + 1] = "function M.up()"

    -- Generate CREATE TABLE statements
    local table_names = {}
    for name in pairs(schema.tables) do
        table_names[#table_names + 1] = name
    end
    table.sort(table_names)

    for _, table_name in ipairs(table_names) do
        local table_def = schema.tables[table_name]
        local create_sql = M.generateCreateTable(table_name, table_def)
        lines[#lines + 1] = "    " .. create_sql
        lines[#lines + 1] = ""
    end

    -- Generate foreign key constraints
    for _, table_name in ipairs(table_names) do
        local table_def = schema.tables[table_name]
        for _, fk in pairs(table_def.foreign_keys) do
            local fk_sql = M.generateForeignKey(fk)
            if fk_sql then
                lines[#lines + 1] = "    " .. fk_sql
            end
        end
    end

    lines[#lines + 1] = "end"
    lines[#lines + 1] = ""
    lines[#lines + 1] = "function M.down()"
    lines[#lines + 1] = "    -- Drop tables in reverse order"

    for i = #table_names, 1, -1 do
        local table_name = table_names[i]
        lines[#lines + 1] = string.format("    jade.dropTable(\"%s\")", table_name)
    end

    lines[#lines + 1] = "end"
    lines[#lines + 1] = ""
    lines[#lines + 1] = "return M"

    return table.concat(lines, "\n")
end

-- Generate CREATE TABLE statement
function M.generateCreateTable(table_name, table_def)
    local lines = {}

    lines[#lines + 1] = string.format("jade.createTable(\"%s\", {", table_name)

    local col_names = {}
    for name in pairs(table_def.columns) do
        col_names[#col_names + 1] = name
    end
    table.sort(col_names)

    for i, col_name in ipairs(col_names) do
        local col = table_def.columns[col_name]
        local col_def = M.generateColumn(col_name, col)
        local suffix = i < #col_names and "," or ""
        lines[#lines + 1] = "        " .. col_def .. suffix
    end

    lines[#lines + 1] = "    })"

    return table.concat(lines, "\n")
end

-- Generate foreign key constraint
function M.generateForeignKey(fk)
    return string.format(
        "jade.addForeignKey(\"%s\", \"%s\", \"%s\", \"%s\")",
        fk.foreign_table,
        fk.column,
        fk.foreign_table,
        fk.foreign_column
    )
end

return M
