describe("Condition", function()
    local Condition = require("jade.query.condition")

    it("creates simple condition", function()
        local cond = Condition.new("age", "=", 18, "users")
        assert.are.equal("age", cond.column)
        assert.are.equal("=", cond.op)
        assert.are.equal(18, cond.value)
        assert.are.equal("users", cond.table_name)
        assert.are.equal("simple", cond.type)
    end)

    it("compiles simple condition with binding", function()
        local cond = Condition.new("age", "=", 18, "users")
        local sql, bindings = cond:compile()
        assert.are.equal('"users"."age" = ?', sql)
        assert.are.same({ 18 }, bindings)
    end)

    it("compiles condition without table prefix", function()
        local cond = Condition.new("name", "=", "Lucas")
        local sql, bindings = cond:compile()
        assert.are.equal('"name" = ?', sql)
        assert.are.same({ "Lucas" }, bindings)
    end)

    it("ANDs two conditions using band operator", function()
        local a = Condition.new("age", ">", 18, "users")
        local b = Condition.new("active", "=", true, "users")
        local combined = a:band(b)
        assert.are.equal("and", combined.type)
    end)

    it("compiles AND condition", function()
        local a = Condition.new("age", ">", 18, "users")
        local b = Condition.new("active", "=", true, "users")
        local combined = a:band(b)
        local sql, bindings = combined:compile()
        assert.are.equal('("users"."age" > ? AND "users"."active" = ?)', sql)
        assert.are.same({ 18, true }, bindings)
    end)

    it("ORs two conditions using bor operator", function()
        local a = Condition.new("role", "=", "admin", "users")
        local b = Condition.new("role", "=", "moderator", "users")
        local combined = a:bor(b)
        assert.are.equal("or", combined.type)
    end)

    it("compiles OR condition", function()
        local a = Condition.new("role", "=", "admin", "users")
        local b = Condition.new("role", "=", "moderator", "users")
        local combined = a:bor(b)
        local sql, bindings = combined:compile()
        assert.are.equal('("users"."role" = ? OR "users"."role" = ?)', sql)
        assert.are.same({ "admin", "moderator" }, bindings)
    end)

    it("compiles nested AND/OR", function()
        local a = Condition.new("age", ">", 18, "users")
        local b = Condition.new("role", "=", "admin", "users")
        local c = Condition.new("role", "=", "moderator", "users")
        local combined = a:band(b:bor(c))
        local sql, bindings = combined:compile()
        assert.are.equal('("users"."age" > ? AND ("users"."role" = ? OR "users"."role" = ?))', sql)
        assert.are.same({ 18, "admin", "moderator" }, bindings)
    end)
end)
