describe("Expression", function()
    local Expression = require("jade.query.expression")
    local Condition = require("jade.query.condition")

    it("creates expression from column", function()
        local expr = Expression.new("age", "users")
        assert.are.equal("age", expr._column)
        assert.are.equal("users", expr._table)
    end)

    it("eq returns Condition", function()
        local expr = Expression.new("age", "users")
        local cond = expr:eq(18)
        assert.are.equal("age", cond.column)
        assert.are.equal("=", cond.op)
        assert.are.equal(18, cond.value)
    end)

    it("lt returns Condition", function()
        local expr = Expression.new("age", "users")
        local cond = expr:lt(65)
        assert.are.equal("<", cond.op)
        assert.are.equal(65, cond.value)
    end)

    it("le returns Condition", function()
        local expr = Expression.new("age", "users")
        local cond = expr:le(65)
        assert.are.equal("<=", cond.op)
    end)

    it("gt returns Condition", function()
        local expr = Expression.new("age", "users")
        local cond = expr:gt(18)
        assert.are.equal(">", cond.op)
        assert.are.equal(18, cond.value)
    end)

    it("ge returns Condition", function()
        local expr = Expression.new("age", "users")
        local cond = expr:ge(18)
        assert.are.equal(">=", cond.op)
    end)

    it("neq returns Condition", function()
        local expr = Expression.new("name", "users")
        local cond = expr:neq("admin")
        assert.are.equal("!=", cond.op)
        assert.are.equal("admin", cond.value)
    end)

    it("like returns Condition", function()
        local expr = Expression.new("name", "users")
        local cond = expr:like("%test%")
        assert.are.equal("LIKE", cond.op)
        assert.are.equal("%test%", cond.value)
    end)

    it("isNull returns Condition", function()
        local expr = Expression.new("name", "users")
        local cond = expr:isNull()
        assert.are.equal("IS", cond.op)
        assert.is_nil(cond.value)
    end)

    it("isNotNull returns Condition", function()
        local expr = Expression.new("name", "users")
        local cond = expr:isNotNull()
        assert.are.equal("IS NOT", cond.op)
    end)

    describe("Expression.raw() injection prevention", function()
        it("blocks semicolon injection with lowercase keywords", function()
            assert.has_error(function()
                Expression.raw("1=1; drop table users")
            end)
        end)

        it("blocks semicolon injection with uppercase keywords", function()
            assert.has_error(function()
                Expression.raw("1=1; DROP TABLE users")
            end)
        end)

        it("blocks UNION SELECT injection", function()
            assert.has_error(function()
                Expression.raw("1 UNION SELECT * FROM users")
            end)
        end)

        it("blocks UNION ALL SELECT injection", function()
            assert.has_error(function()
                Expression.raw("1 UNION ALL SELECT * FROM users")
            end)
        end)

        it("allows simple equality raw expression", function()
            local raw = Expression.raw("id = ?", 1)
            assert.is_truthy(raw)
        end)

        it("allows raw expression with multiple bindings", function()
            local raw = Expression.raw("age BETWEEN ? AND ?", 18, 65)
            assert.is_truthy(raw)
        end)

        it("blocks lowercase union select injection", function()
            assert.has_error(function()
                Expression.raw("1 union select * from users")
            end)
        end)

        it("blocks lowercase union all select injection", function()
            assert.has_error(function()
                Expression.raw("1 union all select * from users")
            end)
        end)

        it("allows legitimate lowercase keywords in raw expressions", function()
            local raw = Expression.raw("name = ?", "test")
            assert.is_truthy(raw)
        end)

        it("allows legitimate lowercase keywords with operators", function()
            local raw = Expression.raw("age > ?", 18)
            assert.is_truthy(raw)
        end)

        it("blocks mixed case union select injection", function()
            assert.has_error(function()
                Expression.raw("1 uNiOn SeLeCt * from users")
            end)
        end)

        it("blocks union select with tab separator", function()
            assert.has_error(function()
                Expression.raw("1 union\tselect * from users")
            end)
        end)

        it("blocks union select with multiple spaces", function()
            assert.has_error(function()
                Expression.raw("1 union    select * from users")
            end)
        end)

        it("blocks mixed case union all select injection", function()
            assert.has_error(function()
                Expression.raw("1 uNiOn aLl SeLeCt * from users")
            end)
        end)

        it("allows legitimate lowercase BETWEEN expression", function()
            local raw = Expression.raw("age between ? and ?", 18, 65)
            assert.is_truthy(raw)
        end)

        it("allows legitimate lowercase IN expression", function()
            local raw = Expression.raw("status in (?, ?)", "active", "pending")
            assert.is_truthy(raw)
        end)

        it("allows legitimate lowercase LIKE expression", function()
            local raw = Expression.raw("name like ?", "%test%")
            assert.is_truthy(raw)
        end)

        it("allows legitimate lowercase IS NULL expression", function()
            local raw = Expression.raw("deleted_at is null")
            assert.is_truthy(raw)
        end)

        it("allows legitimate lowercase ORDER BY in subquery context", function()
            local raw = Expression.raw("(select max(id) from posts) > ?", 0)
            assert.is_truthy(raw)
        end)
    end)
end)
