describe("Expression", function()
    local Expression = require("jade.query.expression")
    local Condition = require("jade.query.condition")

    it("creates expression from column", function()
        local expr = Expression.new("age", "users")
        assert.are.equal("age", expr._column)
        assert.are.equal("users", expr._table)
    end)

    it("eq returns Condition", function()
        local expr = Expression.new("age", "users")
        local cond = expr:eq(18)
        assert.are.equal("age", cond.column)
        assert.are.equal("=", cond.op)
        assert.are.equal(18, cond.value)
    end)

    it("lt returns Condition", function()
        local expr = Expression.new("age", "users")
        local cond = expr:lt(65)
        assert.are.equal("<", cond.op)
        assert.are.equal(65, cond.value)
    end)

    it("le returns Condition", function()
        local expr = Expression.new("age", "users")
        local cond = expr:le(65)
        assert.are.equal("<=", cond.op)
    end)

    it("gt returns Condition", function()
        local expr = Expression.new("age", "users")
        local cond = expr:gt(18)
        assert.are.equal(">", cond.op)
        assert.are.equal(18, cond.value)
    end)

    it("ge returns Condition", function()
        local expr = Expression.new("age", "users")
        local cond = expr:ge(18)
        assert.are.equal(">=", cond.op)
    end)

    it("neq returns Condition", function()
        local expr = Expression.new("name", "users")
        local cond = expr:neq("admin")
        assert.are.equal("!=", cond.op)
        assert.are.equal("admin", cond.value)
    end)

    it("like returns Condition", function()
        local expr = Expression.new("name", "users")
        local cond = expr:like("%test%")
        assert.are.equal("LIKE", cond.op)
        assert.are.equal("%test%", cond.value)
    end)

    it("isNull returns Condition", function()
        local expr = Expression.new("name", "users")
        local cond = expr:isNull()
        assert.are.equal("IS", cond.op)
        assert.is_nil(cond.value)
    end)

    it("isNotNull returns Condition", function()
        local expr = Expression.new("name", "users")
        local cond = expr:isNotNull()
        assert.are.equal("IS NOT", cond.op)
    end)
end)
