-- Tests for seed path validation (#181)
-- Rejects Windows absolute paths, UNC, and directory traversal

describe("Seed - validatePath (security #181)", function()
    local Seed = require("jade.seed")

    it("accepts valid relative paths with .lua extension", function()
        assert.is_true(Seed.validatePath("seeds/users.lua", "lua"))
        assert.is_true(Seed.validatePath("./seeds.lua", "lua"))
    end)

    it("rejects Unix directory traversal (../)", function()
        assert.has_error(function()
            Seed.validatePath("../../etc/passwd.lua", "lua")
        end)
    end)

    it("rejects Windows directory traversal (..\\)", function()
        assert.has_error(function()
            Seed.validatePath("..\\..\\etc\\passwd.lua", "lua")
        end)
    end)

    it("rejects Unix absolute paths", function()
        assert.has_error(function()
            Seed.validatePath("/etc/passwd.lua", "lua")
        end)
    end)

    it("rejects Windows absolute paths with backslash", function()
        assert.has_error(function()
            Seed.validatePath("C:\\evil\\seed.lua", "lua")
        end)
    end)

    it("rejects Windows absolute paths with forward slash", function()
        assert.has_error(function()
            Seed.validatePath("C:/evil/seed.lua", "lua")
        end)
    end)

    it("rejects Windows drive-relative paths", function()
        assert.has_error(function()
            Seed.validatePath("C:foo.lua", "lua")
        end)
    end)

    it("rejects UNC absolute paths", function()
        assert.has_error(function()
            Seed.validatePath("\\\\server\\share\\seed.lua", "lua")
        end)
        assert.has_error(function()
            Seed.validatePath("//server/share/seed.lua", "lua")
        end)
    end)

    it("rejects null bytes in path", function()
        assert.has_error(function()
            Seed.validatePath("seed\0.lua", "lua")
        end)
    end)

    it("rejects paths without required extension", function()
        assert.has_error(function()
            Seed.validatePath("seeds/users.txt", "lua")
        end)
    end)

    it("rejects empty paths", function()
        assert.has_error(function()
            Seed.validatePath("", "lua")
        end)
    end)

    it("rejects non-string paths", function()
        assert.has_error(function()
            Seed.validatePath(123, "lua")
        end)
        assert.has_error(function()
            Seed.validatePath(nil, "lua")
        end)
    end)

    it("uses J5004 typed error with generic security policy message", function()
        local ok, err = pcall(function()
            Seed.validatePath("C:\\evil\\seed.lua", "lua")
        end)
        assert.is_falsy(ok)
        assert.is_truthy(type(err) == "table" and err.code == "J5004")
        local msg = tostring(err)
        assert.is_truthy(msg:find("rejected by security policy"))
        assert.is_falsy(msg:find("null byte"))
        assert.is_falsy(msg:find("traversal"))
    end)

    it("execute rejects absolute Windows path before loadfile", function()
        local ok, err = pcall(function()
            Seed.execute({}, "C:\\evil\\seed.lua")
        end)
        assert.is_falsy(ok)
        assert.is_truthy(type(err) == "table" and err.code == "J5004")
    end)
end)
