local M = {}

local function getMigrationsDir()
    return "migrations"
end

function M.listFiles()
    local dir = getMigrationsDir()
    local files = {}

    local ok, iter, dir_obj = pcall(function()
        local lfs = require("lfs")
        return lfs, lfs.dir(dir)
    end)

    if ok then
        for filename in iter, dir_obj do
            if filename:match("%.lua$") then
                files[#files + 1] = {
                    name = filename,
                    path = dir .. "/" .. filename,
                    timestamp = filename:match("^(%d+)_"),
                }
            end
        end
    else
        -- Fallback: try platform commands (ls on Linux, dir on Windows)
        local handle = io.popen('ls "' .. dir .. '" 2>/dev/null')
        if handle then
            local first = handle:read("*l")
            if first then
                -- ls works (Linux/Mac)
                if first:match("%.lua$") then
                    files[#files + 1] = {
                        name = first,
                        path = dir .. "/" .. first,
                        timestamp = first:match("^(%d+)_"),
                    }
                end
                for filename in handle:lines() do
                    if filename:match("%.lua$") then
                        files[#files + 1] = {
                            name = filename,
                            path = dir .. "/" .. filename,
                            timestamp = filename:match("^(%d+)_"),
                        }
                    end
                end
            end
            handle:close()
        end

        if #files == 0 then
            -- Try Windows dir command
            handle = io.popen('dir "' .. dir .. '" /b 2>nul')
            if handle then
                for filename in handle:lines() do
                    if filename:match("%.lua$") then
                        files[#files + 1] = {
                            name = filename,
                            path = dir .. "/" .. filename,
                            timestamp = filename:match("^(%d+)_"),
                        }
                    end
                end
                handle:close()
            end
        end
    end

    -- Sort by timestamp
    table.sort(files, function(a, b)
        if not a.timestamp then return false end
        if not b.timestamp then return true end
        return a.timestamp < b.timestamp
    end)

    return files
end

function M.load(path)
    local loader, err = loadfile(path)
    if not loader then
        error("Failed to load migration file: " .. tostring(err))
    end
    return loader()
end

function M.writeMigration(name, up_fn, down_fn)
    local dir = getMigrationsDir()
    local timestamp = os.date("%Y%m%d%H%M%S")
    local filename = timestamp .. "_" .. name .. ".lua"
    local path = dir .. "/" .. filename

    local content = string.format([[-- Migration: %s
-- Generated by Jade

local M = {}

function M.up()
%s
end

function M.down()
%s
end

return M
]], name, up_fn, down_fn)

    local file = io.open(path, "w")
    if not file then
        error("Failed to create migration file: " .. path)
    end
    file:write(content)
    file:close()

    return path
end

function M.getTimestamp(name)
    return name:match("^(%d+)_")
end

function M.getNameWithoutTimestamp(name)
    return name:match("^%d+_(.+)$") or name
end

return M
