local errors = require("jade.errors")

local M = {}

local function getMigrationsDir()
    return "migrations"
end

local function sanitizePath(path)
    -- Only allow alphanumeric, underscores, hyphens, dots, slashes, and colons (for Windows drives)
    if not path:match("^[a-zA-Z0-9_%./\\:%-]+$") then
        errors.raise(errors.INVALID_INPUT, {
            details = "Invalid path: contains unsafe characters",
        }, 2)
    end
    return path
end

-- Validate and sanitize file path to prevent directory traversal and arbitrary file loading
-- Exported as M.validatePath for testability
function M.validatePath(path, allowedExtension)
    local function reject()
        errors.raise(errors.INVALID_INPUT, { details = "rejected by security policy" }, 3)
    end
    if type(path) ~= "string" or path == "" then
        reject()
    end

    -- Reject paths with null bytes
    if path:find("\0", 1, true) then
        reject()
    end

    -- Reject directory traversal attempts (.. in any context: ../, ..\, etc.)
    if path:find("..", 1, true) then
        reject()
    end

    -- Reject absolute paths: Unix /, Windows drive (C: or C:\), UNC \\
    if path:match("^/") or path:match("^%a:") or path:match("^\\\\") then
        reject()
    end

    -- Validate extension (allowedExtension must be alphanumeric)
    if allowedExtension and not path:match("%." .. allowedExtension .. "$") then
        reject()
    end

    return true
end

-- Local alias for internal call sites
local validatePath = M.validatePath

-- Whitelist migration names: alphanumeric, underscore, hyphen only (#181)
local function validateMigrationName(name)
    if type(name) ~= "string" or name == "" or not name:match("^[%w%-%_]+$") then
        errors.raise(errors.INVALID_INPUT, { details = "rejected by security policy" }, 3)
    end
    return name
end

function M.listFiles()
    local dir = getMigrationsDir()
    local files = {}

    local ok, lfs_mod = pcall(require, "lfs")
    if ok then
        local iter, start_state = lfs_mod.dir(dir)
        for filename in iter, start_state do
            if filename:match("%.lua$") then
                files[#files + 1] = {
                    name = filename,
                    path = dir .. "/" .. filename,
                    timestamp = filename:match("^(%d+)_"),
                }
            end
        end
    else
        -- Fallback: try platform commands (ls on Linux, dir on Windows)
        local safe_dir = sanitizePath(dir)
        local handle = io.popen('ls "' .. safe_dir .. '" 2>/dev/null')
        if handle then
            local first = handle:read("*l")
            if first then
                -- ls works (Linux/Mac)
                if first:match("%.lua$") then
                    files[#files + 1] = {
                        name = first,
                        path = dir .. "/" .. first,
                        timestamp = first:match("^(%d+)_"),
                    }
                end
                for filename in handle:lines() do
                    if filename:match("%.lua$") then
                        files[#files + 1] = {
                            name = filename,
                            path = dir .. "/" .. filename,
                            timestamp = filename:match("^(%d+)_"),
                        }
                    end
                end
            end
            handle:close()
        end

        if #files == 0 then
            -- Try Windows dir command
            handle = io.popen('dir "' .. safe_dir .. '" /b 2>nul')
            if handle then
                for filename in handle:lines() do
                    if filename:match("%.lua$") then
                        files[#files + 1] = {
                            name = filename,
                            path = dir .. "/" .. filename,
                            timestamp = filename:match("^(%d+)_"),
                        }
                    end
                end
                handle:close()
            end
        end
    end

    -- Sort by timestamp
    table.sort(files, function(a, b)
        if not a.timestamp then return false end
        if not b.timestamp then return true end
        return a.timestamp < b.timestamp
    end)

    return files
end

function M.load(path)
    validatePath(path, "lua")
    local loader, err = loadfile(path)
    if not loader then
        errors.raise(errors.MIGRATION_FILE_INVALID, {
            error = tostring(err),
        }, 2)
    end
    return loader()
end

function M.writeMigration(name, up_fn, down_fn)
    validateMigrationName(name)
    local dir = getMigrationsDir()
    local timestamp = os.date("%Y%m%d%H%M%S")
    local filename = timestamp .. "_" .. name .. ".lua"
    local path = dir .. "/" .. filename

    local content = string.format([[-- Migration: %s
-- Generated by Jade

local M = {}

function M.up()
%s
end

function M.down()
%s
end

return M
]], name, up_fn, down_fn)

    local file = io.open(path, "w")
    if not file then
        errors.raise(errors.MIGRATION_FILE_INVALID, {
            error = "Failed to create migration file: " .. path,
        }, 2)
    end
    file:write(content)
    file:close()

    return path
end

function M.getTimestamp(name)
    return name:match("^(%d+)_")
end

function M.getNameWithoutTimestamp(name)
    return name:match("^%d+_(.+)$") or name
end

return M
